# Generated by Django 3.2.7 on 2021-11-23 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Username')),
                ('holot', models.CharField(blank=True, max_length=50, verbose_name='Họ lót')),
                ('ten', models.CharField(blank=True, max_length=50, verbose_name='Tên')),
                ('email', models.CharField(max_length=300, verbose_name='Email')),
                ('gioitinh', models.CharField(blank=True, max_length=10, null=True, verbose_name='Giới tính')),
                ('diachi', models.CharField(max_length=200, null=True, verbose_name='Địa chỉ')),
                ('addtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Danh sách người dùng',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.FloatField(verbose_name='Tin nhắn')),
                ('addtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày thêm')),
                ('message_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbotapp.register', verbose_name='Người nhắn')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thêm')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Danh sách lịch sử tin nhắn',
            },
        ),
    ]
